/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sdrfood.telas;

import br.com.sdrfood.classes.BackgroundedDesktopPane;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;

/**
 *
 * @author brenno
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        Desktop.setBorder(new BackgroundedDesktopPane());
        this.setExtendedState(Dashboard.MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon(this.getClass().getResource("/br/com/sdrfood/img/back.png"));  
        setIconImage(icon.getImage());
    }
    
    private void centralizaForm(JInternalFrame frame) {
        Dimension desktopSize = Desktop.getSize();
        Dimension jInternalFrameSize = frame.getSize();
        frame.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGarcom = new javax.swing.JMenuItem();
        menuProduto = new javax.swing.JMenuItem();
        menuGerente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        visProd = new javax.swing.JMenuItem();
        visGarcom = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuComissao = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuRel = new javax.swing.JMenuItem();
        menuAbrirConta = new javax.swing.JMenu();
        menuContaAberta = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuSobre = new javax.swing.JMenuItem();
        btnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 493, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenuBar1.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        jMenuBar1.setPreferredSize(new java.awt.Dimension(74, 30));

        jMenu1.setText("Cadastrar");
        jMenu1.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        menuGarcom.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuGarcom.setText("Garçom");
        menuGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGarcomActionPerformed(evt);
            }
        });
        jMenu1.add(menuGarcom);

        menuProduto.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuProduto.setText("Produtos");
        menuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(menuProduto);

        menuGerente.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuGerente.setText("Gerente");
        menuGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGerenteActionPerformed(evt);
            }
        });
        jMenu1.add(menuGerente);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Visualizar");
        jMenu3.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        visProd.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        visProd.setText("Produtos");
        visProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visProdActionPerformed(evt);
            }
        });
        jMenu3.add(visProd);

        visGarcom.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        visGarcom.setText("Garçons");
        visGarcom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visGarcomActionPerformed(evt);
            }
        });
        jMenu3.add(visGarcom);

        jMenuBar1.add(jMenu3);

        jMenu2.setText("Comissão");
        jMenu2.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        menuComissao.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuComissao.setText("Calcular comissão");
        menuComissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuComissaoActionPerformed(evt);
            }
        });
        jMenu2.add(menuComissao);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Relatórios");
        jMenu4.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        menuRel.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuRel.setText("Relatório geral");
        menuRel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuRelActionPerformed(evt);
            }
        });
        jMenu4.add(menuRel);

        jMenuBar1.add(jMenu4);

        menuAbrirConta.setText("Contas");
        menuAbrirConta.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        menuContaAberta.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuContaAberta.setText("Abrir conta");
        menuContaAberta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContaAbertaActionPerformed(evt);
            }
        });
        menuAbrirConta.add(menuContaAberta);

        jMenuItem6.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        jMenuItem6.setText("Contas abertas");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        menuAbrirConta.add(jMenuItem6);

        jMenuBar1.add(menuAbrirConta);

        jMenu6.setText("Mais");
        jMenu6.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N

        menuSobre.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        menuSobre.setText("Sobre");
        menuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSobreActionPerformed(evt);
            }
        });
        jMenu6.add(menuSobre);

        btnSair.setFont(new java.awt.Font("Manjari Bold", 0, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jMenu6.add(btnSair);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGarcomActionPerformed
        CadGarcom garcom = new CadGarcom();
        garcom.setVisible(true);
        Desktop.add(garcom);
        centralizaForm(garcom);
    }//GEN-LAST:event_menuGarcomActionPerformed

    private void menuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProdutoActionPerformed
        CadProduto produto = new CadProduto();
        produto.setVisible(true);
        Desktop.add(produto);
        centralizaForm(produto);
    }//GEN-LAST:event_menuProdutoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void visProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visProdActionPerformed
        VerProdutos prod = new VerProdutos();
        prod.setVisible(true);
        Desktop.add(prod);
        centralizaForm(prod);
    }//GEN-LAST:event_visProdActionPerformed

    private void menuGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGerenteActionPerformed
        CadGerente gerente = new CadGerente();
        gerente.setVisible(true);
        Desktop.add(gerente);
        centralizaForm(gerente);
    }//GEN-LAST:event_menuGerenteActionPerformed

    private void menuComissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuComissaoActionPerformed
        CalcComissao com = new CalcComissao();
        com.setVisible(true);
        Desktop.add(com);
        centralizaForm(com);
    }//GEN-LAST:event_menuComissaoActionPerformed

    private void menuRelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRelActionPerformed
        Relatorios rel = new Relatorios();
        rel.setVisible(true);
        Desktop.add(rel);
        centralizaForm(rel);
    }//GEN-LAST:event_menuRelActionPerformed

    private void menuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSobreActionPerformed
        Sobre sobre = new Sobre();
        sobre.setVisible(true);
        Desktop.add(sobre);
        centralizaForm(sobre);
    }//GEN-LAST:event_menuSobreActionPerformed

    private void menuContaAbertaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContaAbertaActionPerformed
        AbrirConta conta = new AbrirConta();
        conta.setVisible(true);
        Desktop.add(conta);
        centralizaForm(conta);
    }//GEN-LAST:event_menuContaAbertaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        ContasAbertas cAb = new ContasAbertas();
        cAb.setVisible(true);
        Desktop.add(cAb);
        centralizaForm(cAb);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void visGarcomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visGarcomActionPerformed
        VisGarcons garcons = new VisGarcons();
        garcons.setVisible(true);
        Desktop.add(garcons);
        centralizaForm(garcons);
    }//GEN-LAST:event_visGarcomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem btnSair;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu menuAbrirConta;
    private javax.swing.JMenuItem menuComissao;
    private javax.swing.JMenuItem menuContaAberta;
    private javax.swing.JMenuItem menuGarcom;
    private javax.swing.JMenuItem menuGerente;
    private javax.swing.JMenuItem menuProduto;
    private javax.swing.JMenuItem menuRel;
    private javax.swing.JMenuItem menuSobre;
    private javax.swing.JMenuItem visGarcom;
    private javax.swing.JMenuItem visProd;
    // End of variables declaration//GEN-END:variables
}
